name: Update Example Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  push:
    branches:
      - update/exampleSite
jobs:
  update-example-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js dependencies
        run: npm i

      - name: Update example site content
        run: |
          cd exampleSite
          ../node_modules/@zetxek/adritian-theme-helper/dist/scripts/download-content.js

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update example site content"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +'%Y-%m-%d')
          PR_TITLE="${DATE} ExampleSite update"
          PR_BODY="This PR updates the example site with the latest content.\\n\\nOverview of changes:\\n\\n$(git diff --stat HEAD~1)"
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head ${{ github.ref_name }}
