name: Update Example Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  push:
    branches:
      - update/exampleSite
jobs:
  update-example-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js dependencies
        run: npm i

      - name: Update example site content
        run: |
          cd exampleSite
          ../node_modules/@zetxek/adritian-theme-helper/dist/scripts/download-content.js

      - name: Create new branch
        run: |
          DATE=$(date +'%Y-%m-%d')
          BRANCH_NAME="update/exampleSite-${DATE}"
          git checkout -b $BRANCH_NAME

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update example site content"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +'%Y-%m-%d')
          BRANCH_NAME="update/exampleSite-${DATE}"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +'%Y-%m-%d')
          PR_TITLE="ExampleSite content update (${DATE})"
          PR_BODY="This automated PR updates the example site with the latest content from [adritian-demo](https://github.com/zetxek/adritian-demo).
          
          **Overview of changes:**

          <code>
          $(git diff --stat HEAD~1)
          </code>"
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME
