## Updates demo site (https://github.com/zetxek/adritian-demo)
## taken from https://stackoverflow.com/a/68213855/570087

name: Update demo site (on main update)
on:
  push:
    ## run on push to main or a new semantic tag (ie: v1.2.3)
    branches: 
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
          
      - name: Trigger Update Hugo Module workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PRIVATE_TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/zetxek/adritian-demo/actions/workflows/update-hugo-module.yml/dispatches \
            -d '{"ref":"main"}'

      